/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::openapi::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`cenyzlota_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CenyzlotaDateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cenyzlota_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CenyzlotaGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cenyzlota_last_top_count_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CenyzlotaLastTopCountGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cenyzlota_start_date_end_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CenyzlotaStartDateEndDateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cenyzlota_today_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CenyzlotaTodayGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_rates_table_code_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesRatesTableCodeDateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_rates_table_code_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesRatesTableCodeGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_rates_table_code_last_top_count_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesRatesTableCodeLastTopCountGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_rates_table_code_start_date_end_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesRatesTableCodeStartDateEndDateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_rates_table_code_today_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesRatesTableCodeTodayGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_tables_table_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesTablesTableDateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_tables_table_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesTablesTableGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_tables_table_last_top_count_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesTablesTableLastTopCountGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`exchangerates_tables_table_start_date_end_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExchangeratesTablesTableStartDateEndDateGetError {
    UnknownValue(serde_json::Value),
}


pub async fn cenyzlota_date_get(configuration: &configuration::Configuration, date: &str) -> Result<Vec<models::GoldPrice>, Error<CenyzlotaDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_date = date;

    let uri_str = format!("{}/cenyzlota/{date}/", configuration.base_path, date=crate::openapi::apis::urlencode(p_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CenyzlotaDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn cenyzlota_get(configuration: &configuration::Configuration, ) -> Result<Vec<models::GoldPrice>, Error<CenyzlotaGetError>> {

    let uri_str = format!("{}/cenyzlota", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CenyzlotaGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn cenyzlota_last_top_count_get(configuration: &configuration::Configuration, top_count: i32) -> Result<Vec<models::GoldPrice>, Error<CenyzlotaLastTopCountGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_top_count = top_count;

    let uri_str = format!("{}/cenyzlota/last/{topCount}", configuration.base_path, topCount=p_top_count);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CenyzlotaLastTopCountGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn cenyzlota_start_date_end_date_get(configuration: &configuration::Configuration, start_date: &str, end_date: &str) -> Result<Vec<models::GoldPrice>, Error<CenyzlotaStartDateEndDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/cenyzlota/{startDate}/{endDate}/", configuration.base_path, startDate=crate::openapi::apis::urlencode(p_start_date), endDate=crate::openapi::apis::urlencode(p_end_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CenyzlotaStartDateEndDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn cenyzlota_today_get(configuration: &configuration::Configuration, ) -> Result<Vec<models::GoldPrice>, Error<CenyzlotaTodayGetError>> {

    let uri_str = format!("{}/cenyzlota/today", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GoldPrice&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CenyzlotaTodayGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_rates_table_code_date_get(configuration: &configuration::Configuration, table: models::TableType, code: &str, date: &str) -> Result<serde_json::Value, Error<ExchangeratesRatesTableCodeDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_code = code;
    let p_date = date;

    let uri_str = format!("{}/exchangerates/rates/{table}/{code}/{date}/", configuration.base_path, table=p_table.to_string(), code=crate::openapi::apis::urlencode(p_code), date=crate::openapi::apis::urlencode(p_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesRatesTableCodeDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_rates_table_code_get(configuration: &configuration::Configuration, table: models::TableType, code: &str) -> Result<serde_json::Value, Error<ExchangeratesRatesTableCodeGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_code = code;

    let uri_str = format!("{}/exchangerates/rates/{table}/{code}/", configuration.base_path, table=p_table.to_string(), code=crate::openapi::apis::urlencode(p_code));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesRatesTableCodeGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_rates_table_code_last_top_count_get(configuration: &configuration::Configuration, table: models::TableType, code: &str, top_count: i32) -> Result<serde_json::Value, Error<ExchangeratesRatesTableCodeLastTopCountGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_code = code;
    let p_top_count = top_count;

    let uri_str = format!("{}/exchangerates/rates/{table}/{code}/last/{topCount}/", configuration.base_path, table=p_table.to_string(), code=crate::openapi::apis::urlencode(p_code), topCount=p_top_count);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesRatesTableCodeLastTopCountGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_rates_table_code_start_date_end_date_get(configuration: &configuration::Configuration, table: models::TableType, code: &str, start_date: &str, end_date: &str) -> Result<serde_json::Value, Error<ExchangeratesRatesTableCodeStartDateEndDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_code = code;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/exchangerates/rates/{table}/{code}/{startDate}/{endDate}/", configuration.base_path, table=p_table.to_string(), code=crate::openapi::apis::urlencode(p_code), startDate=crate::openapi::apis::urlencode(p_start_date), endDate=crate::openapi::apis::urlencode(p_end_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesRatesTableCodeStartDateEndDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_rates_table_code_today_get(configuration: &configuration::Configuration, table: models::TableType, code: &str) -> Result<models::ExchangeRate, Error<ExchangeratesRatesTableCodeTodayGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_code = code;

    let uri_str = format!("{}/exchangerates/rates/{table}/{code}/today/", configuration.base_path, table=p_table.to_string(), code=crate::openapi::apis::urlencode(p_code));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ExchangeRate`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ExchangeRate`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesRatesTableCodeTodayGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_tables_table_date_get(configuration: &configuration::Configuration, table: models::TableType, date: &str) -> Result<Vec<models::CurrencyExchangeTable>, Error<ExchangeratesTablesTableDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_date = date;

    let uri_str = format!("{}/exchangerates/tables/{table}/{date}/", configuration.base_path, table=p_table.to_string(), date=crate::openapi::apis::urlencode(p_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesTablesTableDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_tables_table_get(configuration: &configuration::Configuration, table: models::TableType) -> Result<Vec<models::CurrencyExchangeTable>, Error<ExchangeratesTablesTableGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;

    let uri_str = format!("{}/exchangerates/tables/{table}/", configuration.base_path, table=p_table.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesTablesTableGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_tables_table_last_top_count_get(configuration: &configuration::Configuration, table: models::TableType, top_count: i32) -> Result<Vec<models::CurrencyExchangeTable>, Error<ExchangeratesTablesTableLastTopCountGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_top_count = top_count;

    let uri_str = format!("{}/exchangerates/tables/{table}/last/{topCount}/", configuration.base_path, table=p_table.to_string(), topCount=p_top_count);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesTablesTableLastTopCountGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn exchangerates_tables_table_start_date_end_date_get(configuration: &configuration::Configuration, table: models::TableType, start_date: &str, end_date: &str) -> Result<Vec<models::CurrencyExchangeTable>, Error<ExchangeratesTablesTableStartDateEndDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_table = table;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/exchangerates/tables/{table}/{startDate}/{endDate}/", configuration.base_path, table=p_table.to_string(), startDate=crate::openapi::apis::urlencode(p_start_date), endDate=crate::openapi::apis::urlencode(p_end_date));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CurrencyExchangeTable&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExchangeratesTablesTableStartDateEndDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

