use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrencyCode {
    // Table A and C currencies (main currencies with bid/ask rates)
    PLN,
    USD,
    EUR,
    GBP,
    CHF,
    AUD,
    CAD,
    HUF,
    JPY,
    CZK,
    DKK,
    NOK,
    SEK,
    XDR,

    // Table A only currencies (mid rates only)
    THB,
    HKD,
    NZD,
    SGD,
    UAH,
    ISK,
    RON,
    BGN,
    TRY,
    ILS,
    CLP,
    PHP,
    MXN,
    ZAR,
    BRL,
    MYR,
    IDR,
    INR,
    KRW,
    CNY,

    // Table B currencies (additional currencies)
    AFN,
    MGA,
    VES,
    BOB,
    CRC,
    SVC,
    NIO,
    GMD,
    MKD,
    DZD,
    BHD,
    IQD,
    JOD,
    KWD,
    LYD,
    RSD,
    TND,
    MAD,
    AED,
    STN,
    BSD,
    BBD,
    BZD,
    BND,
    FJD,
    GYD,
    JMD,
    LRD,
    NAD,
    SRD,
    TTD,
    XCD,
    SBD,
    VND,
    AMD,
    CVE,
    AWG,
    BIF,
    XOF,
    XAF,
    XPF,
    DJF,
    GNF,
    KMF,
    CDF,
    RWF,
    EGP,
    GIP,
    LBP,
    SSP,
    SDG,
    SYP,
    GHS,
    HTG,
    PYG,
    XCG,
    PGK,
    LAK,
    MWK,
    ZMW,
    AOA,
    MMK,
    GEL,
    MDL,
    ALL,
    HNL,
    SLE,
    SZL,
    LSL,
    AZN,
    MZN,
    NGN,
    ERN,
    TWD,
    TMT,
    MRU,
    TOP,
    MOP,
    ARS,
    DOP,
    COP,
    CUP,
    UYU,
    BWP,
    GTQ,
    IRR,
    YER,
    QAR,
    OMR,
    SAR,
    KHR,
    BYN,
    RUB,
    LKR,
    MVR,
    MUR,
    NPR,
    PKR,
    SCR,
    PEN,
    KGS,
    TJS,
    UZS,
    KES,
    SOS,
    TZS,
    UGX,
    BDT,
    WST,
    KZT,
    MNT,
    VUV,
    BAM,
    ZWG,
    PAB,
    ETB,
}

impl CurrencyCode {
    pub fn name(&self) -> &str {
        match self {
            // Table A and C currencies (main currencies with bid/ask rates)
            CurrencyCode::PLN => "Polish Zloty",
            CurrencyCode::USD => "United States Dollar",
            CurrencyCode::EUR => "Euro",
            CurrencyCode::GBP => "British Pound Sterling",
            CurrencyCode::CHF => "Swiss Franc",
            CurrencyCode::AUD => "Australian Dollar",
            CurrencyCode::CAD => "Canadian Dollar",
            CurrencyCode::HUF => "Hungarian Forint",
            CurrencyCode::JPY => "Japanese Yen",
            CurrencyCode::CZK => "Czech Koruna",
            CurrencyCode::DKK => "Danish Krone",
            CurrencyCode::NOK => "Norwegian Krone",
            CurrencyCode::SEK => "Swedish Krona",
            CurrencyCode::XDR => "Special Drawing Rights (IMF)",

            // Table A only currencies (mid rates only)
            CurrencyCode::THB => "Thai Baht",
            CurrencyCode::HKD => "Hong Kong Dollar",
            CurrencyCode::NZD => "New Zealand Dollar",
            CurrencyCode::SGD => "Singapore Dollar",
            CurrencyCode::UAH => "Ukrainian Hryvnia",
            CurrencyCode::ISK => "Icelandic Króna",
            CurrencyCode::RON => "Romanian Leu",
            CurrencyCode::BGN => "Bulgarian Lev",
            CurrencyCode::TRY => "Turkish Lira",
            CurrencyCode::ILS => "Israeli New Shekel",
            CurrencyCode::CLP => "Chilean Peso",
            CurrencyCode::PHP => "Philippine Peso",
            CurrencyCode::MXN => "Mexican Peso",
            CurrencyCode::ZAR => "South African Rand",
            CurrencyCode::BRL => "Brazilian Real",
            CurrencyCode::MYR => "Malaysian Ringgit",
            CurrencyCode::IDR => "Indonesian Rupiah",
            CurrencyCode::INR => "Indian Rupee",
            CurrencyCode::KRW => "South Korean Won",
            CurrencyCode::CNY => "Chinese Yuan Renminbi",

            // Table B currencies (additional currencies)
            CurrencyCode::AFN => "Afghan Afghani",
            CurrencyCode::MGA => "Malagasy Ariary",
            CurrencyCode::VES => "Venezuelan Bolívar Soberano",
            CurrencyCode::BOB => "Bolivian Boliviano",
            CurrencyCode::CRC => "Costa Rican Colón",
            CurrencyCode::SVC => "Salvadoran Colón",
            CurrencyCode::NIO => "Nicaraguan Córdoba Oro",
            CurrencyCode::GMD => "Gambian Dalasi",
            CurrencyCode::MKD => "Macedonian Denar",
            CurrencyCode::DZD => "Algerian Dinar",
            CurrencyCode::BHD => "Bahraini Dinar",
            CurrencyCode::IQD => "Iraqi Dinar",
            CurrencyCode::JOD => "Jordanian Dinar",
            CurrencyCode::KWD => "Kuwaiti Dinar",
            CurrencyCode::LYD => "Libyan Dinar",
            CurrencyCode::RSD => "Serbian Dinar",
            CurrencyCode::TND => "Tunisian Dinar",
            CurrencyCode::MAD => "Moroccan Dirham",
            CurrencyCode::AED => "UAE Dirham",
            CurrencyCode::STN => "São Tomé and Príncipe Dobra",
            CurrencyCode::BSD => "Bahamian Dollar",
            CurrencyCode::BBD => "Barbadian Dollar",
            CurrencyCode::BZD => "Belize Dollar",
            CurrencyCode::BND => "Brunei Dollar",
            CurrencyCode::FJD => "Fijian Dollar",
            CurrencyCode::GYD => "Guyanese Dollar",
            CurrencyCode::JMD => "Jamaican Dollar",
            CurrencyCode::LRD => "Liberian Dollar",
            CurrencyCode::NAD => "Namibian Dollar",
            CurrencyCode::SRD => "Surinamese Dollar",
            CurrencyCode::TTD => "Trinidad and Tobago Dollar",
            CurrencyCode::XCD => "East Caribbean Dollar",
            CurrencyCode::SBD => "Solomon Islands Dollar",
            CurrencyCode::VND => "Vietnamese Dong",
            CurrencyCode::AMD => "Armenian Dram",
            CurrencyCode::CVE => "Cape Verdean Escudo",
            CurrencyCode::AWG => "Aruban Florin",
            CurrencyCode::BIF => "Burundian Franc",
            CurrencyCode::XOF => "CFA Franc BCEAO",
            CurrencyCode::XAF => "CFA Franc BEAC",
            CurrencyCode::XPF => "CFP Franc",
            CurrencyCode::DJF => "Djiboutian Franc",
            CurrencyCode::GNF => "Guinean Franc",
            CurrencyCode::KMF => "Comorian Franc",
            CurrencyCode::CDF => "Congolese Franc",
            CurrencyCode::RWF => "Rwandan Franc",
            CurrencyCode::EGP => "Egyptian Pound",
            CurrencyCode::GIP => "Gibraltar Pound",
            CurrencyCode::LBP => "Lebanese Pound",
            CurrencyCode::SSP => "South Sudanese Pound",
            CurrencyCode::SDG => "Sudanese Pound",
            CurrencyCode::SYP => "Syrian Pound",
            CurrencyCode::GHS => "Ghanaian Cedi",
            CurrencyCode::HTG => "Haitian Gourde",
            CurrencyCode::PYG => "Paraguayan Guaraní",
            CurrencyCode::XCG => "Caribbean Guilder",
            CurrencyCode::PGK => "Papua New Guinean Kina",
            CurrencyCode::LAK => "Lao Kip",
            CurrencyCode::MWK => "Malawian Kwacha",
            CurrencyCode::ZMW => "Zambian Kwacha",
            CurrencyCode::AOA => "Angolan Kwanza",
            CurrencyCode::MMK => "Myanmar Kyat",
            CurrencyCode::GEL => "Georgian Lari",
            CurrencyCode::MDL => "Moldovan Leu",
            CurrencyCode::ALL => "Albanian Lek",
            CurrencyCode::HNL => "Honduran Lempira",
            CurrencyCode::SLE => "Sierra Leonean Leone",
            CurrencyCode::SZL => "Eswatini Lilangeni",
            CurrencyCode::LSL => "Lesotho Loti",
            CurrencyCode::AZN => "Azerbaijani Manat",
            CurrencyCode::MZN => "Mozambican Metical",
            CurrencyCode::NGN => "Nigerian Naira",
            CurrencyCode::ERN => "Eritrean Nakfa",
            CurrencyCode::TWD => "New Taiwan Dollar",
            CurrencyCode::TMT => "Turkmenistan Manat",
            CurrencyCode::MRU => "Mauritanian Ouguiya",
            CurrencyCode::TOP => "Tongan Pa'anga",
            CurrencyCode::MOP => "Macanese Pataca",
            CurrencyCode::ARS => "Argentine Peso",
            CurrencyCode::DOP => "Dominican Peso",
            CurrencyCode::COP => "Colombian Peso",
            CurrencyCode::CUP => "Cuban Peso",
            CurrencyCode::UYU => "Uruguayan Peso",
            CurrencyCode::BWP => "Botswana Pula",
            CurrencyCode::GTQ => "Guatemalan Quetzal",
            CurrencyCode::IRR => "Iranian Rial",
            CurrencyCode::YER => "Yemeni Rial",
            CurrencyCode::QAR => "Qatari Rial",
            CurrencyCode::OMR => "Omani Rial",
            CurrencyCode::SAR => "Saudi Riyal",
            CurrencyCode::KHR => "Cambodian Riel",
            CurrencyCode::BYN => "Belarusian Ruble",
            CurrencyCode::RUB => "Russian Ruble",
            CurrencyCode::LKR => "Sri Lankan Rupee",
            CurrencyCode::MVR => "Maldivian Rufiyaa",
            CurrencyCode::MUR => "Mauritian Rupee",
            CurrencyCode::NPR => "Nepalese Rupee",
            CurrencyCode::PKR => "Pakistani Rupee",
            CurrencyCode::SCR => "Seychellois Rupee",
            CurrencyCode::PEN => "Peruvian Sol",
            CurrencyCode::KGS => "Kyrgyzstani Som",
            CurrencyCode::TJS => "Tajikistani Somoni",
            CurrencyCode::UZS => "Uzbekistani Sum",
            CurrencyCode::KES => "Kenyan Shilling",
            CurrencyCode::SOS => "Somali Shilling",
            CurrencyCode::TZS => "Tanzanian Shilling",
            CurrencyCode::UGX => "Ugandan Shilling",
            CurrencyCode::BDT => "Bangladeshi Taka",
            CurrencyCode::WST => "Samoan Tālā",
            CurrencyCode::KZT => "Kazakhstani Tenge",
            CurrencyCode::MNT => "Mongolian Tögrög",
            CurrencyCode::VUV => "Vanuatu Vatu",
            CurrencyCode::BAM => "Bosnia and Herzegovina Convertible Mark",
            CurrencyCode::ZWG => "Zimbabwe Gold",
            CurrencyCode::PAB => "Panamanian Balboa",
            CurrencyCode::ETB => "Ethiopian Birr",
        }
    }
}
