use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrencyCode {
    PLN,
    USD,
    EUR,
    GBP,
    CHF,
    THB,
    AUD,
    HKD,
    CAD,
    NZD,
    SGD,
    HUF,
    UAH,
    JPY,
    CZK,
    DKK,
    ISK,
    NOK,
    SEK,
    RON,
    BGN,
    TRY,
    ILS,
    CLP,
    PHP,
    MXN,
    ZAR,
    BRL,
    MYR,
    IDR,
    INR,
    KRW,
    CNY,
    XDR,
}

impl CurrencyCode {
    pub fn name(&self) -> &str {
        match self {
            CurrencyCode::PLN => "Polish Zloty",
            CurrencyCode::USD => "United States Dollar",
            CurrencyCode::EUR => "Euro",
            CurrencyCode::GBP => "British Pound Sterling",
            CurrencyCode::CHF => "Swiss Franc",
            CurrencyCode::THB => "Thai Baht",
            CurrencyCode::AUD => "Australian Dollar",
            CurrencyCode::HKD => "Hong Kong Dollar",
            CurrencyCode::CAD => "Canadian Dollar",
            CurrencyCode::NZD => "New Zealand Dollar",
            CurrencyCode::SGD => "Singapore Dollar",
            CurrencyCode::HUF => "Hungarian Forint",
            CurrencyCode::UAH => "Ukrainian Hryvnia",
            CurrencyCode::JPY => "Japanese Yen",
            CurrencyCode::CZK => "Czech Koruna",
            CurrencyCode::DKK => "Danish Krone",
            CurrencyCode::ISK => "Icelandic Króna",
            CurrencyCode::NOK => "Norwegian Krone",
            CurrencyCode::SEK => "Swedish Krona",
            CurrencyCode::RON => "Romanian Leu",
            CurrencyCode::BGN => "Bulgarian Lev",
            CurrencyCode::TRY => "Turkish Lira",
            CurrencyCode::ILS => "Israeli New Shekel",
            CurrencyCode::CLP => "Chilean Peso",
            CurrencyCode::PHP => "Philippine Peso",
            CurrencyCode::MXN => "Mexican Peso",
            CurrencyCode::ZAR => "South African Rand",
            CurrencyCode::BRL => "Brazilian Real",
            CurrencyCode::MYR => "Malaysian Ringgit",
            CurrencyCode::IDR => "Indonesian Rupiah",
            CurrencyCode::INR => "Indian Rupee",
            CurrencyCode::KRW => "South Korean Won",
            CurrencyCode::CNY => "Chinese Yuan Renminbi",
            CurrencyCode::XDR => "Special Drawing Rights (IMF)",
        }
    }
}
