/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyExchangeTable {
    #[serde(rename = "table", skip_serializing_if = "Option::is_none")]
    pub table: Option<models::TableType>,
    /// Table number
    #[serde(rename = "no", skip_serializing_if = "Option::is_none")]
    pub no: Option<String>,
    #[serde(rename = "tradingDate", skip_serializing_if = "Option::is_none")]
    pub trading_date: Option<String>,
    /// Date representing when the currency exchange was published.
    #[serde(rename = "effectiveDate", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    #[serde(rename = "rates", skip_serializing_if = "Option::is_none")]
    pub rates: Option<Vec<models::ExchangeRate>>,
}

impl CurrencyExchangeTable {
    pub fn new() -> CurrencyExchangeTable {
        CurrencyExchangeTable {
            table: None,
            no: None,
            trading_date: None,
            effective_date: None,
            rates: None,
        }
    }
}

