/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyExchangeTable {
    #[serde(rename = "table")]
    pub table: models::TableType,
    /// Table number
    #[serde(rename = "no")]
    pub no: String,
    #[serde(rename = "tradingDate", skip_serializing_if = "Option::is_none")]
    pub trading_date: Option<String>,
    /// Date representing when the currency exchange was published.
    #[serde(rename = "effectiveDate", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    #[serde(rename = "rates")]
    pub rates: Vec<models::ExchangeRate>,
}

impl CurrencyExchangeTable {
    pub fn new(
        table: models::TableType,
        no: String,
        rates: Vec<models::ExchangeRate>,
    ) -> CurrencyExchangeTable {
        CurrencyExchangeTable {
            table,
            no,
            trading_date: None,
            effective_date: None,
            rates,
        }
    }
}
