/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeRate {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "bid", skip_serializing_if = "Option::is_none")]
    pub bid: Option<f64>,
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<f64>,
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<f64>,
}

impl ExchangeRate {
    pub fn new(currency: String, code: String) -> ExchangeRate {
        ExchangeRate {
            currency,
            code,
            bid: None,
            ask: None,
            mid: None,
        }
    }
}

