/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoldPrice {
    /// Date representing when the gold price was published.
    #[serde(rename = "data")]
    pub data: String,
    /// The price of 1g of gold (of 1000 millesimal fineness) calculated at NBP.
    #[serde(rename = "cena")]
    pub cena: f64,
}

impl GoldPrice {
    pub fn new(data: String, cena: f64) -> GoldPrice {
        GoldPrice {
            data,
            cena,
        }
    }
}

