/*
 * NBP API
 *
 * NBP (Narodowy Bank Polski) currency exchange API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoldPrice {
    /// Date representing when the gold price was published.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// The price of 1g of gold (of 1000 millesimal fineness) calculated at NBP.
    #[serde(rename = "cena", skip_serializing_if = "Option::is_none")]
    pub cena: Option<String>,
}

impl GoldPrice {
    pub fn new() -> GoldPrice {
        GoldPrice {
            data: None,
            cena: None,
        }
    }
}

